# .travis.yml file based on:
# https://gist.github.com/dan-blanchard/7045057

language: python
python:
  - 3.6
env:
  - CONDA_TYPE=miniconda CONDA_VERS=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - CONDA_TYPE=miniconda CONDA_VERS=https://repo.continuum.io/miniconda/Miniconda3-4.5.11-Linux-x86_64.sh

before_install:
  # install git lfs and fetch test data
  - if [ ! -f $HOME/download/git-lfs-linux-amd64-2.0.2.tar.gz ]; then
      pushd $HOME/download;
      wget https://github.com/github/git-lfs/releases/download/v2.0.2/git-lfs-linux-amd64-2.0.2.tar.gz;
      popd;
    fi
  - tar xzf $HOME/download/git-lfs-linux-amd64-2.0.2.tar.gz
  - (cd git-lfs-2.0.2 && PREFIX=$HOME/.local ./install.sh)
  - export PATH=$HOME/.local/bin:$PATH
  - git lfs pull

install:
  # Setup anaconda. See http://conda.pydata.org/docs/travis.html

  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - echo "Using $CONDA_TYPE"
  - wget $CONDA_VERS -O miniconda.sh
  - bash miniconda.sh -h | sed '4q;d'
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Create conda environment with dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy bokeh h5py jupyter scipy networkx
  - source activate test-environment
  - pip install coveralls
  - pip install git+https://github.com/BBN-Q/bbndb.git
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then  pip install pygsti; fi

script:
  - coverage run -m unittest discover
after_script:
  - coveralls

# necessary to run on new container-based infrastructure
sudo: false

cache:
  directories:
    - $HOME/download
    - $HOME/.cache/pip
